### ISSUE TITLE
[Question] of computing scores

### ISSUE THREAD

**Issue by NatureGeorge** [biocryst/biozernike#8]
Hi! I am using the `biozernike` library to perform some comparisons between PDB structures. I would like to do some calculations between subsets of assemblies and get some distance/similarity scores. I found no direct portal to get the `weighted GEO + weighted CN` score (*the distance function for the composite BioZernike feature vectors*) as described in `Real time structural search of the Protein Data Bank. Guzenko D, Burley SK, Duarte JM. PLoS Computational Biology 2020` or `Geom Score & Total Score` that provided by shape.rcsb.org. 

So I tried this code:

```java
...
public class JustForTest {
...

      public Descriptor prepareDescriptor(Structure structure, DescriptorConfig config) throws Exception {
		Atom[] reprAtoms = StructureTools.getRepresentativeAtomArray(structure);
		Point3d[] reprPoints = Calc.atomsToPoints(reprAtoms);
		String[] resNames = Arrays.stream(reprAtoms).map(a -> a.getGroup().getPDBName()).toArray(String[]::new);
		return new Descriptor(reprPoints,resNames,config);
      }

      public void test_Descriptor() throws Exception {
		Structure s1 = StructureIO.getStructure("1a0u");
		Structure s2 = StructureIO.getStructure("4hhb");
		DescriptorConfig config = new DescriptorConfig(
                		JustForTest.class.getResourceAsStream("/descriptor.properties"), 
                		EnumSet.allOf(DescriptorMode.class));
		double[] geo_weight = config.coefficientsGeometry;
                List<double[]> cn_weights = config.coefficientsZernike;
		Descriptor sd1 = prepareDescriptor(s1, config);
		Descriptor sd2 = prepareDescriptor(s2, config);
		double[] md1 = sd1.getMomentDescriptor();
		double[] md2 = sd2.getMomentDescriptor();
		double[] geo1 = sd1.getGeometryDescriptor();
		double[] geo2 = sd2.getGeometryDescriptor();

		double geo_dist = 0;
		for (int k = 0; k < geo_weight.length; k++) {
			geo_dist += geo_weight[k] * 2 * Math.abs(geo1[k] - geo2[k]) / (Math.abs(geo1[k]) + Math.abs(geo2[k]) + 1);
		}

                double cn_dist = 0;
                int index = 0;
		for (int j = 0; j < cn_weights.size(); j++) {
			double[] cn_weight = cn_weights.get(j);
			for (int k = 0; k < cn_weight.length; k++) {
				cn_dist += cn_weight[k] * Math.abs(md1[index]-md2[index]);
                                index++;
			}
		}
       }
```

The `geo_dist` and `cn_dist` as computed above are around 0.0865 and 1.1722 respectively (total: 1.2534), and the scores provided by shape.rcsb.org are (Geom Score: 97.41) and (Total Score: 86.97). So here is my question: am I doing right? And does the computed distances equivalent to the Scores? If so, what is the formula to transform them?

**Comment by biocryst** [comment]
Hi!

You are doing everything right as far as I can see, to calculate the **distance** between the descriptors.
There are two things at play here:

1) The scores on the website are transformed into **similarity**: 100 if identical (distance=0), 0 if not considered similar (distance=threshold).  So the final score is obtained from 100*(threshold-distance)/threshold, where the value of the threshold varies according to whether we want a 'strict' or a 'relaxed' search.  In fact, the descriptor.properties file contains two sample pairs of thresholds 'threshold.geometry' and 'threshold.zernike' for such transformation.

2) The coefficients and the thresholds used by the rcsb shape search service might be different from the ones in this repository. If I remember correctly, the distance measure/thresholds for the validation paper were fitted on the CATH families, and the ones used in the search were fitted to the set of unique (by shape) assemblies selected from PDB. However, these differences are not too significant and the resulting distances (or similarities) will highly correlate.

**Comment by NatureGeorge** [comment]
Thanks for your reply! Now I know how to compute the Geometry Score:

```java
double geo_threshold = config.thresholdSets[0][0];
double geo_score = 100 * (geo_threshold-geo_dist) / geo_threshold;
```

But I am still not sure of the exact definition of the Total Score. Does it just stands for the CN-based part or stand for the sum of the Geo part and CN-based part? Because I saw this distance function for the composite BioZernike feature vectors in the paper: ![image](https://user-images.githubusercontent.com/43134199/132005548-cafb9e75-4af6-4294-89df-5c9a50104233.png)

```java
double zernike_threshold = config.thresholdSets[0][1];
// if just stands for the CN-based part
double total_score = 100 * (zernike_threshold-cn_dist) / zernike_threshold;
// if stands for the sum of Geo part and CN-based part
double total_score = 100 * (zernike_threshold-(geo_dist+cn_dist)) / zernike_threshold;
```

Appreciate your time.
